version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: flask_ex1

    ports:
    - 5431:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8079:8080